#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re

ARGS_ESPERADOS = {
    "NICK": 1,
    "PING": 1,
    "PRIVMSG": 2,
    "JOIN": 1,
    "PART": 1,
}

#nicks atualmente em uso (mapeado para a conexão)
NICKS = {}

# Chave: canal.lower() -> valor: lista de nicks nessse canal
CANAIS = {}

#conexoes atualmente sendo utilizadas
CONNECTIONS = []

# Servidor envia msg
def enviar(conexao, msg):
    # Str -> bytes
    conexao.enviar((msg + '\r\n').encode('utf-8'))

def liberar_nick(conexao):
    if conexao.nick != '*':
        NICKS.pop(conexao.nick.lower(), None)

def sanitize_string_data(dados):
    return dados.decode("utf-8").strip()

# Valida nome de usuários e canais
def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None

#funcao handler para quando o usuario nao usar um dos comandos definidos
def stupid_user():
    print("Available commands: NICK, PING, PRIVMSG, JOIN, PART")

#funcao handler para NICK
def nick(conexao, novo_nick):
    print("NICKS:", NICKS)

    #verificacao do nick
    if not validar_nome(novo_nick.encode("utf-8")):
        enviar(conexao, f":server 432 {conexao.nick} {novo_nick} :Erroneous nickname")
        return

    #verificacao se ja existe
    if novo_nick.lower() in NICKS:
        enviar(conexao, f":server 433 {conexao.nick} {novo_nick} :Nickname is already in use")
        return

    nick_antigo = conexao.nick

    if nick_antigo != '*':
        enviar(conexao, f":{nick_antigo} NICK {novo_nick}")
        liberar_nick(conexao)      # libera o nick antigo
    else:
        enviar(conexao, f":server 001 {novo_nick} :Welcome")
        enviar(conexao, f":server 422 {novo_nick} :MOTD File is missing")
 
    NICKS[novo_nick.lower()] = conexao     # reserva o nick novo
    conexao.nick = novo_nick       # atualiza o estado da conexão

#funcao handler para PING
def ping(conexao, payload):
    enviar(conexao, f":server PONG server :{payload}")

#funcao handler para PRIVMSG
def privmsg(conexao, destinatario, conteudo):
    if conteudo.startswith(":"):
        conteudo = conteudo[1:]

    msg = f":{conexao.nick} PRIVMSG {destinatario} :{conteudo}"

    # Se destinatario for um canal
    if destinatario.startswith("#"):
        nick_membros_canal = CANAIS.get(destinatario.lower())
        if nick_membros_canal is None:
            return
        for nick_membro in nick_membros_canal:
            # Não enviar msg a si mesmo
            if nick_membro == conexao.nick.lower():
                continue
            conexao_membro = NICKS.get(nick_membro)
            if conexao_membro is not None:
                enviar(conexao_membro, msg)
        return
    
    destino = NICKS.get(destinatario.lower())
    if destino is None:
        return
    
    enviar(destino, msg)

#funcao handler para JOIN
def join(conexao, canal):
    # Verifica se é um canal e se o nome é válido 
    if not canal.startswith("#") or not validar_nome(canal[1:].encode("utf-8")):
        enviar(f":server 403 {canal} :No such channel")

    # Adiciona chave canal.lower() em CANAIS, se canal.lower() não está lá
    canal_lower = canal.lower()
    if canal_lower not in CANAIS:
        CANAIS[canal_lower] = []

    # Adiciona o usuário na lista de nicks do canal
    if conexao.nick.lower() not in CANAIS[canal_lower]:
        CANAIS[canal_lower].append(conexao.nick.lower())

    # Para cada membro do canal, envia quem entrou
    for nick_membro in CANAIS[canal_lower]:
        conexao_membro = NICKS.get(nick_membro)
        if conexao_membro is not None:
            enviar(conexao_membro, f":{conexao.nick} JOIN :{canal}")

#funcao handler para PART
def part(channel):
    print(channel)

# Separa os tipos de mensagem e direciona para cada handler
# command: tipo de comando nick,ping ...
# rest: string[]
def message_protocol(conexao, command, rest):

    esperado = ARGS_ESPERADOS.get(command)

    if esperado is None or len(rest) < esperado:
        return stupid_user()

    cases = {
        "NICK": lambda: nick(conexao, rest[0]),
        "PING": lambda: ping(conexao, rest[0]),
        "PRIVMSG": lambda: privmsg(conexao, rest[0], rest[1]),
        "JOIN": lambda: join(conexao, rest[0]),
        "PART": lambda: part(rest[0]),
    }

    # cases.get(command, stupid_user) retorna a função associada,
    # ou a função stupid_user se a chave não existir
    return cases.get(command, stupid_user)()

def sair(conexao):
    print(conexao, 'conexão fechada')
    
    if conexao.nick != '*':
        liberar_nick(conexao)
    
    CONNECTIONS.remove(conexao)
    print(CONNECTIONS)
    conexao.fechar()

def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)

    # Adiciona as mensagens enviadas no buffer
    # Se vier quebrado, quando chegar '\r\n', a msg vai estar pronta
    conexao.dados_residuais += dados

    # "linha 1\r\nlinha 2\r\nlinha 3\r\n" -> 3 linhas prontas
    # split('\r\n', 1) -> linha_pronta == "linha 1" e 
    # conexao.dados_residuais == "linha 2\r\nlinha 3\r\n"
    # Repete o processo
    while b'\r\n' in conexao.dados_residuais:
        linha_pronta, conexao.dados_residuais = conexao.dados_residuais.split(b'\r\n', 1)
        processar_linha(conexao, linha_pronta)

def processar_linha(conexao, linha):
    #strip para tirar o \r\n no final do ultimo argumento
    # Bytes -> string
    string_data = sanitize_string_data(linha)

    #divide a string em no máximo 3 partes, permitindo até 3 argumentos em 1 comando
    words = string_data.split(maxsplit=2)

    if not words:
        return stupid_user()

    command = words[0]
    rest = words[1:]

    message_protocol(conexao, command, rest)

def conexao_aceita(conexao):
    print(conexao, 'nova conexão')

    # Novos atributos para o objeto conexao
    # O atributo 'dados_residuais' vai armazenar as mensagens enviadas em uma conexão
    # (podem vir quebradas, ou não, e vão sendo armazenadas nele)
    conexao.nick = '*'
    conexao.dados_residuais = b''

    conexao.registrar_recebedor(dados_recebidos)
    CONNECTIONS.append(conexao)
    print(CONNECTIONS)

# Gambiarra p/ teste funcionar no meu pc.
# Aparentemente no python 3.14 não pode chamar asyncio.get_event_loop()
# Se não tiver um event loop criado
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)

servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
